#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include "system.h"

typedef struct
{
	unsigned char COORDINATOR[8];
	unsigned char KC1[8];
	unsigned char K1[8];
	unsigned char K2[8];
	unsigned char K3[8];
	unsigned char BROADCAST[8];
	unsigned char UNKNOWN16[2];
} ADDRESST;

//TELEMETRIES
	#define TELEMETRIES_ALTITUDE_ESTIMATED 0x00
	#define TELEMETRIES_ALTITUDE 0x01
	#define TELEMETRIES_ELEVATOR_SPEED 0x02
	#define TELEMETRIES_AILERON_SPEED 0x03
	#define TELEMETRIES_ELEVATOR_SPEED_ESTIMATED 0x04
	#define TELEMETRIES_AILERON_SPEED_ESTIMATED 0x05
	#define TELEMETRIES_ELEVATOR_POSITION 0x06
	#define TELEMETRIES_AILERON_POSITION 0x07
	#define TELEMETRIES_ALTITUDE_CONTROLLER_OUTPUT 0x08
	#define TELEMETRIES_ALTITUDE_SPEED 0x09
	#define TELEMETRIES_AILERON_CONTROLLER_OUTPUT 0x0A
	#define TELEMETRIES_ELEVATOR_CONTROLLER_OUTPUT 0x0B
	#define TELEMETRIES_ALTITUDE_SETPOINT 0x0C
	#define TELEMETRIES_ELEVATOR_POS_SETPOINT 0x0D
	#define TELEMETRIES_AILERON_POS_SETPOINT 0x0E
	#define TELEMETRIES_ELEVATOR_ACC 0x0F
	#define TELEMETRIES_AILERON_ACC 0x10
	#define TELEMETRIES_VALID_GUMSTIX 0x11
	#define TELEMETRIES_OUTPUT_THROTTLE 0x12
	#define TELEMETRIES_OUTPUT_ELEVATOR 0x13
	#define TELEMETRIES_OUTPUT_AILERON 0x14
	#define TELEMETRIES_OUTPUT_RUDDER 0x15
	#define TELEMETRIES_BLOB_ELEVATOR 0x16
	#define TELEMETRIES_BLOB_AILERON 0x17
	#define TELEMETRIES_BLOB_ALTITUDE 0x18
	#define TELEMETRIES_PITCH_ANGLE 0x19
	#define TELEMETRIES_ROLL_ANGLE 0x1A
	#define TELEMETRIES_ELEVATOR_SHIFT 0x1B
	#define TELEMETRIES_AILERON_SHIFT 0x1C
	#define TELEMETRIES_ELEVATOR_ACC_INPUT 0x1D
	#define TELEMETRIES_ELEVATOR_ACC_ERROR 0x1E
	#define TELEMETRIES_AILERON_ACC_INPUT 0x1F
	#define TELEMETRIES_AILERON_ACC_ERROR 0x20

	#define TELEMETRY_VARIABLES 33

//ON-OFF
	#define DISABLE 0
	#define ENABLE 1
	
//CONTROLLERS
	#define CONTROLLERS_OFF 0x01
	#define CONTROLLERS_ALTITUDE 0x02
	#define CONTROLLERS_MPC 0x03
	
//LANDING STATES	
	#define LANDING_ON_GROUND 0x00
	#define LANDING_LANDING 0x01
	#define LANDING_STABILIZATION 0x02
	#define LANDING_TAKE_OFF 0x03
	#define LANDING_FLIGHT 0x04
	
//COMMANDS
	#define COMMANDS_TELEMETRY_COORDINATOR 0x01
	#define COMMANDS_LANDING 0x02
	#define COMMANDS_CONTROLLERS 0x03
	#define COMMANDS_TRAJECTORY_POINTS 0x04
	#define COMMANDS_POSITION_SLAVE_SET 0x05
	#define COMMANDS_TIME 0x06
	#define COMMANDS_POSITION_SET 0x07
	
//GET STATUS	
	#define GET_STATUS 0xFF


extern ADDRESST ADDRESS;
void constInit();

#endif /* CONSTANTS_H_ */