#!/bin/sh

case $1 in
   start)
      pid=`ps aux | grep "/bin/sh /opt/tracker/tracker.sh" | grep -v grep | awk '{print $2}'`
      if [ -n "$pid" ]
      then
	 echo "tracker is already running"
      else
	 /opt/tracker/tracker.sh 2>&1 1>/var/log/tracker.log &
	 echo "tracker started"
      fi
      ;;
   stop)
      pid=`ps aux | grep "/bin/sh /opt/tracker/tracker.sh" | grep -v grep | awk '{print $2}'`
      if [ -n "$pid" ]; then 
	 kill -9 $pid; 
	 killall -9 tracker.sh;
	 kill -9 `pidof /opt/tracker/tracker`
	 echo "tracker.sh killed"
      else
	 echo "tracker is not runnig"
      fi
      ;;
   restart)
      pid=`ps aux | grep "/bin/sh /opt/tracker/tracker.sh" | grep -v grep | awk '{print $2}'`
      if [ -n "$pid" ]; then 
	 kill -9 $pid; 
	 echo "tracker.sh killed"
	 killall -9 tracker.sh;
	 kill -9 `pidof /opt/tracker/tracker`
      else
	 echo "tracker is not runnig"
      fi
      /opt/tracker/tracker.sh 2>&1 1>/var/log/tracker.log &
      echo "tracker started"
      ;;
   status)
      ;;
   *)
esac
